#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
package_install tmux

say "Download tpm the tmux plugin manager"
if [ -d ~/.tmux/plugins/tpm ]; then
  say "tpm already downloaded"
else
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  say "tpm downloaded"
fi

say "Configure tmux"
mkdir -p ~/.config/tmux
cp ./tmux.conf ~/.config/tmux/tmux.conf
