#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
sudo flatpak update
package_install steam-devices
flatpak install flatpak install flathub com.valvesoftware.Steam
flatpak install com.valvesoftware.Steam.CompatibilityTool.Proton-GE
flatpak install flathub net.lutris.Lutris
