#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  url="https://github.com/neovim/neovim/releases/download/v${version}/nvim-linux64.tar.gz"
  curl -sL "$url" | sudo tar -xzv --directory /usr/local/bin/
  sudo ln -s /usr/local/bin/nvim-linux64/bin/nvim /usr/local/bin/nvim
  popd
}

say "Install neovim"
github_install_helper nvim neovim/neovim

say "Configure neovim"
mkdir -p ~/.config/nvim
cp ./init.lua ~/.config/nvim/init.lua
cp -r ./lua ~/.config/nvim/

