#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
package_install distrobox

say "Configure backports repository"
sudo cp ./debian-12-backports.list /etc/apt/sources.list.d/debian-12-backports.list
sudo apt update

